config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

urlpatterns += static(
      settings.MEDIA_URL,
      document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path, include
from . import views 

app_name = 'portfolio'
urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('activities', views.activities_page_view, name='activities'),
    path('index', views.index, name='index'),
    path('escola', views.escola_page_view, name='escola'),
    path('academia', views.academia_page_view, name='academia'),
    path('web', views.web_page_view, name='web'),
    path('news', views.news_page_view, name='news'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('nova/', views.nova_page_view, name='nova'),
    path('blogueira', views.blogueira_page_view, name='blogueira'),
    path('edita/<int:tarefa_id>', views.edita_page_view, name='edita'),
    path('apaga/<int:tarefa_id>', views.apaga_page_view, name='apaga'),
    path('publication', views.publication, name='publication'),
    path('novoPost/', views.novo_post_page_view, name='novopost'),
    path('editPost/<int:post_id>', views.edit_post_page_view, name='editPost'),
    path('apagaPost/<int:post_id>', views.apaga_post_page_view, name='apagaPost'),
    #path('like_post/<int:post_id>/<str:action>/', views.like_post, name='like_post'),
    path('comentario', views.comentario, name='comentario'),
]

portfolio/models.py
# models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=250)
    autor = models.CharField(max_length=100)
    content = models.CharField(max_length=850)
    createTime = models.DateTimeField(auto_now_add=True)
    imagem = models.ImageField(upload_to='images/', null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    createTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class Lingua(models.Model):
    nome = models.CharField(max_length=100)
    criador = models.CharField(max_length=100)
    linguagens_usadas = models.CharField(max_length=100)
    descricao = models.TextField()

    def __str__(self):
        return self.nome


class Competencia(models.Model):
    nome = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nome 


class Professor(models.Model):
    nome = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    post = models.ForeignKey(Post, null=False, on_delete=models.CASCADE, related_name='professor')

    def __str__(self):
        return self.nome


class Pessoa(models.Model):
    nome = models.CharField(max_length=100)
    link = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Disciplina(models.Model):
    nome = models.CharField(max_length=100)
    ano = models.IntegerField()
    semestre = models.IntegerField()
    ECTS = models.IntegerField()
    ano_letivo = models.CharField(max_length=20)
    topicos_abordados = models.CharField(max_length=300)
    professores = models.ManyToManyField(Pessoa, null=False, related_name='disciplina')

    def __str__(self):
        return self.nome


class Tarefa(models.Model):
    titulo = models.CharField(max_length=30)
    prioridade = models.IntegerField(default=1)
    concluida = models.BooleanField(default=False)
    criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo[:20]

users/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Professor, Tarefa, Post


class Professor(ModelForm):
    class Meta:
            model = Professor
            fields = '__all__'


class TarefaForm(ModelForm):
    class Meta:
        model = Tarefa
        fields = '__all__'
        exclude = ['concluida']

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição da tarefa...'}),
            'prioridade': forms.NumberInput(attrs={'class': 'form-control', 'max': 3, 'min': 1}),
        }

        labels = {
            'titulo': 'Título',
            'concluido': 'Concluída',
        }

        # o dicionário help_texts contém, para um atributo, um texto auxiliar a apresentar por baixo da janela de inserção
        help_texts = {
            'prioridade': 'prioridade: baixa=1, media=2, alta=3',
        }


class PostForm(ModelForm):
    class Meta:
            model = Post
            fields = '__all__'

            widgets = {
                'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição do Post...'}),
            }

            labels = {
                'titulo': 'Título',
                'descricao': 'Descricao',
            }

            # o dicionário help_texts contém, para um atributo, um texto auxiliar a apresentar por baixo da janela de inserção
            help_texts = {
                'decricao': 'descreva o seu post',
            }

portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from .forms import TarefaForm, PostForm
from .models import Post, Lingua, Competencia, Professor, Disciplina, Pessoa, Tarefa, Comment
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout


def home_page_view(request):
    return render(request, 'portfolio/home.html')


def activities_page_view(request):
    return render(request, 'portfolio/activities.html')


def blogueira_page_view(request):
    return render(request, 'portfolio/blogueira.html')


def web_page_view(request):
    return render(request, 'portfolio/web.html')


def news_page_view(request):
    return render(request, 'portfolio/news.html')

def index_page_view(request):
    return render(request, 'portfolio/index.html')


def escola_page_view(request):
    print("ola")
    return render(request, 'portfolio/contact.html')


def academia_page_view(request):
    disciplina = Disciplina.objects.all()
    context = {
        'disciplina': disciplina
    }
    return render(request, 'portfolio/academia.html', context)


def publication(request):
    publication = Post.objects.all()
    context = {
        'publication': publication
    }
    return render(request, 'portfolio/pubs.html', context)


def comentario(request):
    comentario = Comment.objects.all()
    context = {
        'comentario': comentario
    }
    return render(request, 'portfolio/pubs.html', context)


def post(request):
    post = Post.objects.all()
    return render(request, 'portfolio/contact.html', {post})


def linguas(request):
    linguas = Lingua.objects.all()
    return render(request, 'portfolio/contact.html', {linguas})


def competencias(request):
    competencias = Competencia.objects.all()
    return render(request, 'portfolio/contact.html', {competencias})


def pessoas(request):
    pessoas = Pessoa.objects.all()
    return render(request, 'portfolio/contact.html', {pessoas})


def disciplinas(request):
    disciplina = Disciplina.objects.all()
    return render(request, 'portfolio/contact.html', disciplina)


def professores(request):
    professores = Professor.objects.all()
    if request.method == "POST":
        nome = request.POST["nome_professor"]
        email = request.POST["email_professor"]
        post = request.POST["post_professor"]
    Professor.objects.create(nome=nome, email=email, post=post)
    return HttpResponseRedirect(reverse('portfolio:escola', professores))


def Professor_view(request):
    Events = Professor.objects.all()
    context = {
        'Event': Events
    }
    return render(request=request, template_name="contact.html", context=context)


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('portfolio:login'))
    return render(request, "portfolio/login.html")


def login_view(request):
    print("I'm in")
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,
                            username=username,
                            password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('portfolio:index'))
        else:
            return render(request, "portfolio/login.html", {
                'message': "Invalid credentials"
            })
    return render(request, "portfolio/login.html")


def logout_view(request):
    logout(request)
    return render(request, 'portfolio/login.html'), {
        "message": "logged out."
    }


def blogueira_page_view(request):
    context = {'tarefas': Tarefa.objects.all()}
    return render(request, 'portfolio/blogueira.html', context)


def nova_page_view(request):
    form = TarefaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blogueira'))

    context = {'form': form}

    return render(request, 'portfolio/nova.html')


def apaga_page_view(request, tarefa_id):
    Tarefa.objects.get(id=tarefa_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blogueira'))


def edita_page_view(request, tarefa_id):
    tarefa = Tarefa.objects.get(id=tarefa_id)
    form = TarefaForm(request.POST or None, instance=tarefa)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blogueira'))

    context = {'form': form, 'tarefa_id': tarefa_id}
    return render(request, 'portfolio/edita.html', context)


def novo_post_page_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blogueira'))

    context = {'form': form}

    return render(request, 'portfolio/novoPost.html')


@login_required
def edit_post_page_view(request, post_id):
    print("Mina")
    post = Post.objects.get(id=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:publication'))

    context = {'form': form, 'post_id': post_id}
    return render(request, 'portfolio/editPost.html', context)


def apaga_post_page_view(request, post_id):
    Post.objects.get(id=post_id).delete()
    return HttpResponseRedirect(reverse('portfolio:publication'))


def like_post(request, post_id, action):
    post = Post.objects.get(id=post_id)
    if action == 'like':
        post.likes.add(request.user)
    elif action == 'unlike':
        post.likes.remove(request.user)
    return JsonResponse({'message': 'success'})

users/views.py
from django.shortcuts import render

# Create your views here.

portfolio/templates/portfolio/academia.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block header %}
{% endblock%}

{% block main %}
    <section class="services services-section bd-container" id="services">
        <h2 class="services-title">Unidades Curriculares</h2>

        <div class="services__container grid">
            {% for i in disciplina %}
                {% if i.ano == 1 %}
                <div class="services__data">
                    <h3 class="services__title">{{ i.nome }}</h3>
                    <p><b>ECTS: </b>{{ i.ECTS }}</p>
                    <p><b>Ano: </b>{{ i.ano }}</p>
                    <p><b>Ano letivo: </b>{{ i.ano_letivo }}</p>
                    <p><b>Tópicos: </b>{{ i.topicos_abordados }}</p>
                    <p><b>Docentes: </b>{{ i.professores }}</p>
                </div>
                {% endif %}
            {% endfor %}
            {% for i in disciplina %}
               {% if i.ano == 2 %}
                <div class="services__data">
                    <h3 class="services__title">{{ i.nome }}</h3>
                    <p><b>ECTS: </b>{{ i.ECTS }}</p>
                    <p><b>Ano: </b>{{ i.ano }}</p>
                    <p><b>Ano letivo: </b>{{ i.ano_letivo }}</p>
                    <p><b>Tópicos: </b>{{ i.topicos_abordados }}</p>
                    <p><b>Docentes: </b>{{ i.professores }}</p>
                </div>
                {% endif %}
            {% endfor %}
            {% for i in disciplina %}
               {% if i.ano == 3 %}
                <div class="services__data">
                    <h3 class="services__title">{{ i.nome }}</h3>
                    <p><b>ECTS: </b>{{ i.ECTS }}</p>
                    <p><b>Ano: </b>{{ i.ano }}</p>
                    <p><b>Ano letivo: </b>{{ i.ano_letivo }}</p>
                    <p><b>Tópicos: </b>{{ i.topicos_abordados }}</p>
                    <p><b>Docentes: </b>{{ i.professores }}</p>
                </div>
                {% endif %}
            {% endfor %}
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/activities.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block header %}
{% endblock%}

{% block main %}
    <section class="section bd-container" id="teste">
        <div>
            <img id="imagem" src="{% static 'portfolio/images/proj3.jpg' %}" alt="Imagem" class="activities__img">
            <h1 id="frase">Insere o teu nome</h1>
            <form>
                <input type="text" id="nome" placeholder="Insira o seu nome" autofocus>
                <input type="submit">
            </form>
        </div>
    </section>
    
    <section class="section container_calculator bd-container">
        <div class="about__container grid">
            <h1> Bora fazer algumas contas!</h1>

            <div class="calculator">
                <form action="">
                    <div class="display">
                        <input type="text" name="display">
                    </div>
                    <div>
                        <input type="button" value="AC" onclick="display.value = '' " class="operator">
                        <input type="button" value="DE" onclick="display.value = display.value.toString().slice(0,-1) " class="operator">
                        <input type="button" value="." onclick="display.value += '.' " class="operator">
                        <input type="button" value="/" onclick="display.value += '/' " class="operator">
                    </div>
                    <div>
                        <input type="button" value="7" onclick="display.value += '7' ">
                        <input type="button" value="8" onclick="display.value += '8' ">
                        <input type="button" value="9" onclick="display.value += '9' ">
                        <input type="button" value="*" onclick="display.value += '*' " class="operator">
                    </div>
                    <div>
                        <input type="button" value="4" onclick="display.value += '4' ">
                        <input type="button" value="5" onclick="display.value += '5' ">
                        <input type="button" value="6" onclick="display.value += '6' ">
                        <input type="button" value="-" onclick="display.value += '-' " class="operator">
                    </div>
                    <div>
                        <input type="button" value="1" onclick="display.value += '1' ">
                        <input type="button" value="2" onclick="display.value += '2' ">
                        <input type="button" value="3" onclick="display.value += '3' ">
                        <input type="button" value="+" onclick="display.value += '+' " class="operator">
                    </div>
                    <div>
                        <input type="button" value="00" onclick="display.value += '00' ">
                        <input type="button" value="0" onclick="display.value += '0' ">
                        <input type="button" value="=" onclick="display.value = eval(display.value)" class="equal operator">
                    </div>
                </form>
            </div>
        </div>
    </section>

    <section>
        <div class="parallax-container">
            <div class="parallax-image first">
                <img src="{% static 'portfolio/images/rembkg-removebg-preview.png' %}" alt="">
            </div>
            <div class="parallax-image second">
                <img src="{% static 'portfolio/images/rembkg-removebg-preview.png' %}" alt="">
            </div>
            <div class="parallax-image third">
                <img src="{% static 'portfolio/images/rembkg-removebg-preview.png' %}" alt="">
            </div>
            <div class="parallax-text" id="parallax-text">
                <h1 id="opening">Welcome to My Parallax Page</h1>
                <p>This page is under maitenance</p>
            </div>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/editPost.html
{% extends 'portfolio/layoutDjando.html' %}
{% load static %}

{% block header %}
{% endblock%}

{% block main %}
    <section class="jumbotron blog__container bd-container">
        <div>
            <h3>Post</h3>
            <form action="{% url 'portfolio:editPost' post_id %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <a href="{% url 'portfolio:publication' %}" role="button" class="btn btn-warning">Cancelar</a>

                <input type="submit" value="Gravar" class="btn btn-success">
                <a href="{% url 'portfolio:apagaPost' post_id %}" role="button" class="btn btn-danger">Apagar</a>
            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/edita.html
{% extends 'portfolio/layoutDjando.html' %}
{% load static %}

{% block header %}
{% endblock%}

{% block main %}
    <section class="jumbotron blog__container bd-container">
        <div>
            <h3>Tarefa</h3>
            <form action="{% url 'portfolio:edita' tarefa_id %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}

                <a href="{% url 'portfolio:blogueira' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" value="Gravar" class="btn btn-success" >
                <a href="{% url 'portfolio:apaga' tarefa_id %}" role="button" class="btn btn-danger">Apagar</a>
            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/layout.html
{% load static %}


<body>
    <!--ScrollTop-->
    <a href="#" class="scrolltop" id="scroll-top">
        <i class='bx bx-chevron-up scrolltop__icon'></i>
    </a>
    <header class="header" id="header">
        <title>Okica's</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
        <meta name="author" content="Joana Okica">
        <meta name="description" content="Portfolio de Joana Okica. Licenciada em Línguas para Relações Internacionais e estudande de licenciatura em Engenharia Informática">
        <meta name="keywords" content="Html, Student projects, Js, Css">
        <link rel="stylesheet" href="{% static 'portfolio\css\style.css' %}">
        <link rel="stylesheet" href="{% static 'portfolio\css\swiper-bundle.min.css' %}">
        <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.2.0/fonts/remixicon.css" rel="stylesheet">


        <nav class="nav container">
            <a href="{% url 'portfolio:index' %}" class="nav__logo">Okica's</a>

            <div class="nav__menu" id="nav-menu">
                <ul class="nav__list" id="nav-list">
                    <li>
                       <a href= "{% url 'portfolio:home' %}" class="nav__link">About Me</a>
                    </li>
                    <li>
                        <a href= "{% url 'portfolio:activities' %}" class="nav__link">Activities</a>
                    </li>
                    <li class="dd__item">
                        <div class="nav__link">
                            About this Website
                            <i  class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
                        <ul class="dd__menu">
                            <li class="dd__subitem">
                                <a href= "{% url 'portfolio:web' %}" class="dd__link">
                                    <i class="ri-pie-chart-line"></i>Tecnologias
                                </a>
                            </li>
                            <li class="dd__subitem">
                                <a href="{% url 'portfolio:web' %}" class="dd__link">
                                     <i class="ri-pie-chart-line"></i>Website
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="dd__item">
                        <div class="nav__link">
                            Blog
                            <i  class="ri-arrow-down-s-line dropdown__arrow"></i>
                        </div>
                        <ul class="dd__menu">
                            <li class="dd__subitem">
                                <a href="{% url 'portfolio:blogueira' %}" class="dd__link">
                                    <i class="ri-pie-chart-line"></i>Tarefas
                                </a>
                            </li>
                            <li class="dd__subitem">
                                <a href="{% url 'portfolio:publication' %}" class="dd__link">
                                     <i class="ri-pie-chart-line"></i>Publications
                                </a>
                            </li>
                            <li class="dd__subitem">
                                <a href="{% url 'portfolio:news' %}" class="dd__link">
                                     <i class="ri-pie-chart-line"></i>News
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href= "{% url 'portfolio:academia' %}" class="nav__link">Academia</a>
                    </li>
                    <li>
                        <a href= "{% url 'portfolio:login' %}" class="nav__link">Login</a>
                    </li>
                    <li onclick="myFunction()">
                        <a href="{% url 'portfolio:escola' %}" class="nav__link">Contact</a>
                    </li>
                </ul>

                <div class="nav__close" id="nav-close">
                    <i class="ri-close-line"></i>
                </div>
            </div>

            <div class="nav__btns">
                <i class="ri-moon-line change-theme" id="theme-button"></i>

                <div class="nav__toggle" id="nav-toggle">
                    <i class="ri-menu-line"></i>
                </div>
            </div>
        </nav>
    </header>

    <main>
        {% block main %} {% endblock %}
    </main>

    <footer>
      {% block footer %} {% endblock %}
    </footer>

</body>

<script>
    const currentDate = new Date();
    const dateElement = document.getElementById("date");
    dateElement.innerHTML = currentDate.toDateString();
</script>

<script>
    const p = document.querySelector('.home__description');
    p.classList.add('visible');
</script>

<script src="{%  static 'portfolio/css/swiper-bundle.min.js' %}"></script>

<!--Sim eu sei que podia fazer tudo num só scrip mas é mais facil se estiver organizado em varios. Pelo menos por agora-->
<script>
    /*==================== SHOW MENU ====================*/
    const navMenu = document.getElementById('nav-menu'),
        navToggle = document.getElementById('nav-toggle'),
        navClose = document.getElementById('nav-close')

    /*===== MENU SHOW =====*/
    /* Validate if constant exists */
    if (navToggle) {
        navToggle.addEventListener('click', () => {
            navMenu.classList.add('show-menu')
        })
    }

    /*===== MENU HIDDEN =====*/
    /* Validate if constant exists */
    if (navClose) {
        navClose.addEventListener('click', () => {
            navMenu.classList.remove('show-menu')
        })
    }

    /*==================== REMOVE MENU MOBILE ====================*/
    const navLink = document.querySelectorAll('.nav__link')

    function linkAction() {
        const navMenu = document.getElementById('nav-menu')
        // When we click on each nav__link, we remove the show-menu class
        navMenu.classList.remove('show-menu')
    }
    navLink.forEach(n => n.addEventListener('click', linkAction))
</script>

<script>
    /*==================== DARK LIGHT THEME ====================*/
    const themeButton = document.getElementById('theme-button')
    const darkTheme = 'dark-theme'
    const iconTheme = 'ri-sun-line'

    // Previously selected topic (if user selected)
    const selectedTheme = localStorage.getItem('selected-theme')
    const selectedIcon = localStorage.getItem('selected-icon')

    // We obtain the current theme that the interface has by validating the dark-theme class
    const getCurrentTheme = () => document.body.classList.contains(darkTheme) ? 'dark' : 'light'
    const getCurrentIcon = () => themeButton.classList.contains(iconTheme) ? 'ri-moon-line' : 'ri-sun-line'

    // We validate if the user previously chose a topic
    if (selectedTheme) {
        // If the validation is fulfilled, we ask what the issue was to know if we activated or deactivated the dark
        document.body.classList[selectedTheme === 'dark' ? 'add' : 'remove'](darkTheme)
        themeButton.classList[selectedIcon === 'ri-moon-line' ? 'add' : 'remove'](iconTheme)
    }

    // Activate / deactivate the theme manually with the button
    themeButton.addEventListener('click', () => {
        // Add or remove the dark / icon theme
        document.body.classList.toggle(darkTheme)
        themeButton.classList.toggle(iconTheme)
        // We save the theme and the current icon that the user chose
        localStorage.setItem('selected-theme', getCurrentTheme())
        localStorage.setItem('selected-icon', getCurrentIcon())
    })
</script>

<script>
    // Wait for window load
    window.onload = function () {
        // Hide preloader when page is loaded
        document.querySelector('.preloader').style.display = 'none';

        // Set up motto array
        const mottos = ['live', 'love', 'learn', 'code', 'repeat'];
        let i = 0;

        // Display mottos one by one
        setInterval(function () {
            document.querySelector('.motto').innerHTML = mottos[i];
            i++;
            if (i >= mottos.length) {
                i = 0;
            }
        }, 1000);
    }
</script>

<script>
    var swiper = new Swiper(".discover__container", {
        effect: "coverflow",
        grabCursor: true,
        centeredSlides: true,
        slidesPerView: "auto",
        loop: true,
        spaceBetween: 32,
        coverflowEffect: {
            rotate: 0,
        },
    });
</script>
<script>
    // When the user clicks on div, open the popup
    function myFunction() {
        var popup = document.getElementById("myPopup");
        popup.classList.toggle("show");
    }

    function scrollTop() {
        const scrollTop = document.getElementById('scroll-top')
        if (this.scrollY >= 560) scrollTop.classList.add('show-scroll'); else scrollTop.classList.remove('scroll')
    }
    window.addEventListener('scroll',scrollTop)
</script>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<script href="{% static 'portfolio/css/mixitup.min.js'%}"></script>
<script>
    // Get the input field and the frase element
    const inputNome = document.getElementById("nome");
    const fraseElement = document.getElementById("frase");

    // Listen for input event on the input field
    inputNome.addEventListener("input", function () {
        // Get the value of the input field
        const nome = inputNome.value;

        // Update the text in the frase element
        fraseElement.textContent = nome;
    });
</script>

</html>

portfolio/templates/portfolio/nova.html
{% extends 'portfolio/layoutDjando.html' %}
{% load static %}

{% block header %}
{% endblock%}

{% block main %}
    <section class="jumbotron blog__container bd-container">
        <div class="">
            <h1>Nova Tarefas</h1>
            <form action="{% url 'portfolio:nova' %}" method="POST">
            {% csrf_token %}
                {{ form.as_p }}

                <a href="{% url 'portfolio:blogueira' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" value="Gravar" class="btn btn-success" >
            </form>
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/pubs.html
{% extends 'portfolio/layoutDjando.html' %}


{% load static %}

{% block header %}
{% endblock%}

{% block main %}
    <section class="jumbotron blog__container bd-container">
        <h1>Publications</h1>
        {% for post in publication %}
            <div class="post">
                <h2>{{ post.title }}</h2>
                <p>Autor: {{ post.autor }}</p>
                <p>{{ post.content }}</p>
                <img src="{{ post.imagem.url }}" alt="{{ post.title }}" class="post-image">
                <p>Total de Likes: {{ post.likes }}</p>

                {% if user.is_authenticated %}
                    <a href="{% url 'portfolio:editPost' post.id %}" class="btn btn-warning  btn-sm" style="float: right; margin-right: 10px">Editar</a>
                {% endif %}
            </div>
        {% endfor %}
    </section>
{% endblock %}

portfolio/templates/portfolio/user.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block header %}
{% endblock%}

{% block main %}
    <section class="jumbotron blog__container bd-container">
        <div class="">
            <h1>Bem Vindo : {{ request.user.username }}</h1>
            <ul>
                <li>Username: {{ request.user.username }}</li>
            </ul>
            <a href="{% url 'portfolio:logout' %}">Logout</a>
        </div>
    </section>
{% endblock %}